application: aiutateste
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: test.app  
- url: /css
  static_dir: css
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest